# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 14.x
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: |
          echo 'console.log(secrets.TEST)'
          echo 'console.log(process.env.TEST)' > test.js
          TEST=abcd1234 node test.js
        env:
          TEST: ${{ secrets.TEST }}
